version: '2'
services:
  prometheus:
    image: qnib/prometheus
    hostname: prometheus
    container_name: prometheus
    networks:
     - compose-net
    ports:
     - 9090:9090
    environment:
     - DC_NAME=compose
     - CONSUL_CLUSTER_IPS=consul

#  cadvisor: 
#    hostname: cadvisor
#    container_name: cadvisor
#    image: google/cadvisor:latest
#    networks:
#     - compose-net
#    volumes:
#     - /:/rootfs:ro
#     - /var/run:/var/run:rw
#     - /sys:/sys:ro
#     - /var/lib/docker/:/var/lib/docker:ro
#    ports:
#     - 8888:8080

networks:
  compose-net:
    external: true
