version: '2'
services:
  qcollect: 
    image: qnib/qcollect
    hostname: qcollect
    container_name: qcollect
    networks:
      - compose-net
    environment:
      - CONSUL_DC_NAME=compose
      - DC_NAME=compose
      - QCOLLECT_INFLUXDB_ENABLED=true
      - QCOLLECT_INFLUXDB_SERVER=influxdb
      - DOCKER_HOST=unix:///var/run/docker.sock
      - QCOLLECT_INTERVAL=2
      - CONSUL_CLUSTER_IPS=consul
      - CONSUL_NODE_NAME=qcollect
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  compose-net:
    external: true
